apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft
  namespace: minecraft
spec:
  encryptedData:
    rcon-password: AgB/NOELYsIoh3dHWcugXtcfC2j/rKsLzfiaOzALXc8lWxcJj30ZK/7LTyMMR8VC3BslCt1qeq+3V1BJ9WaUEVxfDo1AdcTvxKJZ1rhsUD//RlsmZ3g3qL+6y3n2cu1w2rJyx210xvRsf4m014+KPBPe8iUBqX9EOmwVPkKvwMqSW8iHDC97pOD16XbPH4vU2TxA+m85UFSsAXEs/iVYLE9VbSANSP508cDbKjI+xUWek/il9kEM1bjFADQGJ4h1E3dQhx3xFxlHnI7hNCNRDcrB33swc2vGPogjS8nO8t+UYxyIEIMlkgoyo3jLMy2Ok0izkawKw8aoz/Gbens6iMpPSjz0Aanq0rWbqltC9QikXsdzk12eF3eefHLCvF0A/rcBBy+ed0vSMqxgt6LN+9FRaOKBf2QpjQwiqoU3N8rRlMH+BbT1U2HFSxvcMhnacjy2G2QLTr032vQh7OUrYTna7kKkkBkyqJhZOsIuxhxMWS6jrjZgb+B6qSNh+mWH/XMtJMvfsJFGQgdUCII8T+YSqhKrS/mR/zLhJ6xSzCtNtTDtJwRJhH9XLVkLS6QSovVvtEnKKb5bU9lpacQoA9D82EFbOcL5hvCFXWiCEfxpbkMJXOteJOM8pl/kTGhWQX3zEf6zmnOWiz3aLTPLAON+x6IOoz5JAqiCj+8aUrPawOWy6XT/x7VRRCXbaKQivCDemOvBaaSYiw==
  template:
    metadata:
      name: minecraft
      namespace: minecraft
