apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: default
  source:
    chart: minecraft
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 4.4.0
    helm:
      parameters:
        - name: minecraftServer.worldSaveName
          value: "connerworld"
        - name: startupProbe.initialDelaySeconds
          value: "100"
        - name: startupProbe.failureThreshold
          value: "60"
        - name: startupProbe.periodSeconds
          value: "5"
        - name: resources.requests.memory
          value: "5Gi"
        - name: resources.requests.cpu
          value: "1200m"
        - name: minecraftServer.eula
          value: "TRUE"
        - name: minecraftServer.serviceType
          value: LoadBalancer
        # check out persistence, and rcon secret
        - name: minecraftServer.rcon.enabled
          value: "true"
        - name: minecraftServer.rcon.serviceType
          value: LoadBalancer
        - name: minecraftServer.rcon.existingSecret
          value: minecraft
        - name: minecraftServer.maxPlayers
          value: "10"
        - name: minecraftServer.memory
          value: "5000M"
        - name: persistence.dataDir.enabled
          value: "true"
        - name: persistence.dataDir.Size
          value: "3Gi"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minecraft

