apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-jiva
  namespace: argocd
spec:
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: k8s/argo-apps/openebs-jiva-patches
      repoURL: https://github.com/plockc/plockc.github.io/
      targetRevision: HEAD
      directory:
        include: 'helmchart.yaml'
    - path: k8s/argo-apps/openebs-jiva-patches
      repoURL: https://github.com/plockc/plockc.github.io/
      targetRevision: HEAD
      directory:
        include: 'patches.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
