apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  local:
    v4pool:
      aggregation: default
      pool: 192.168.14.10-192.168.15.254
      subnet: 192.168.14.0/23
