apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rcon
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: rcon-web-admin
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: "1.0.0"
    helm:
      parameters:
        - name: rconWeb.passwordExistingSecret
          value: rcon
        - name: rconWeb.isAdmin
          value: "true"
        # think this is workaround to disable websocket env vars
        - name: ingress.enabled
          value: "true"
        - name: service.type
          value: LoadBalancer
        - name: rconWeb.rconPasswordExistingSecret
          value: minecraft
        - name: rconWeb.rconHost
          value: minecraft-minecraft-rcon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minecraft
