apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rcon
  namespace: argocd
spec:
  project: default
  source:
    chart: rcon-web-admin
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: "1.0.0"
    helm:
      parameters:
        - name: service.type
          value: LoadBalancer
        - name: rconWeb.rconPasswordExistingSecret
          value: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minecraft
