apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.22.1
    helm:
      parameters:
        - name: ui.enabled
          value: "true"
        - name: ui.serviceType
          value: LoadBalancer
        - name: ui.externalPort
          value: "443"
  ignoreDifferences:
    - name: vault-agent-injector-cfg
      group: "*"
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
