apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-jiva-helmchart
  namespace: argocd
spec:
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  project: default
  source:
    - chart: jiva
      repoURL: https://openebs.github.io/jiva-operator
      targetRevision: v3.4.0
      helm:
        parameters: [] 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels: 
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true

