apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-jiva-patches
  namespace: argocd
spec:
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: k8s/argo-apps/openebs-jiva-patches/csi-node-host-pid.yaml
      repoURL: https://github.com/plockc/plockc.github.io/
      targetRevision: HEAD
    - path: k8s/argo-apps/openebs-jiva-patches/iscsi-admin-configmap.yaml
      repoURL: https://github.com/plockc/plockc.github.io/
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

